### Understanding Tensorflow based on Deep-Learning-with-TensorFlow

#### Chapter 2

In [19]:
import tensorflow as tf

with tf.Session() as sess:
    x = tf.placeholder(tf.float32,[3],name="x")
    y = tf.placeholder(tf.float32,[1],name="y")
    z = tf.constant(2.0)
    y = x*z
    x_in = [300,400,500]
    y_output = sess.run(y,{x: x_in})
    print(y_output)

[ 600.  800. 1000.]


In [14]:
import tensorflow as tf
import numpy as np
a = 1
b = 2

x = tf.placeholder(tf.float32,[a,b])
y = tf.add(x,x)

data = np.random.rand(a,b)
print("Data",data)
sess = tf.Session()
print("Result",sess.run(y,feed_dict={x: data}))


Data [[0.3804653  0.05917821]]
Result [[0.7609306  0.11835643]]


In [22]:
import tensorflow as tf
constant_a = tf.constant([100])
constant_b = tf.constant([200])
constant_c = tf.constant([3])

sum_ = tf.add(constant_a,constant_b)
mul_ = tf.multiply(constant_a,constant_c)

with tf.Session() as sess:
    result = sess.run([sum_,mul_])
    print("Sum",result[0])
    print("Multi",result[1])

Sum [300]
Multi [300]


##### Single Neuron

In [27]:
import tensorflow as tf

weight = tf.Variable(1.0, name="weight")
input_value = tf.Variable(0.5, name="input_value")
expected_output = tf.constant(0.0, name="expected_output")

model = tf.multiply(input_value,weight, "model")  # input * weight 

loss_function = tf.pow(expected_output - model, 2, name="loss_function") #Mean Sqaure Error L2

optimizer = tf.train.GradientDescentOptimizer(0.025).minimize(loss_function)

for value in [input_value, weight, expected_output, model, loss_function]:
    tf.summary.scalar(value.op.name, value)
    print(tf.summary.scalar(value.op.name, value))

summaries = tf.summary.merge_all()
sess = tf.Session()

summary_writer = tf.summary.FileWriter('log_simple_stats', sess.graph)

sess.run(tf.global_variables_initializer())

for i in range(100):
    summary_writer.add_summary(sess.run(summaries), i)
    sess.run(optimizer)
    



Tensor("input_value_5_2:0", shape=(), dtype=string)
Tensor("weight_5_2:0", shape=(), dtype=string)
Tensor("expected_output_5_2:0", shape=(), dtype=string)
Tensor("model_5_2:0", shape=(), dtype=string)
Tensor("loss_function_5_2:0", shape=(), dtype=string)


##### Tensorflow Counter

In [32]:
import tensorflow as tf

value = tf.Variable(0, name="value")
one = tf.constant(1)
new_value = tf.add(value, one)
update_value = tf.assign(value, new_value)

initialize_var = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(initialize_var)
    print(sess.run(value))
    for _ in range(10):
        sess.run(update_value)
        print(sess.run(value))



0
1
2
3
4
5
6
7
8
9
10


##### with numpy

In [39]:
import tensorflow as tf
import numpy as np

#tensore 1d con valori costanti
tensor_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
tensor_1d = tf.constant(tensor_1d)
with tf.Session() as sess:
    print(tensor_1d.get_shape())
    print(sess.run(tensor_1d))
    print("\n")
#tensore 2d con valori variabili
tensor_2d = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])
tensor_2d = tf.Variable(tensor_2d)
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(tensor_2d.get_shape())
    print(sess.run(tensor_2d))
    print("\n")
    
tensor_3d = np.array([[[ 0,  1,  2],[ 3,  4,  5],[ 6,  7,  8]],
                      [[ 9, 10, 11],[12, 13, 14],[15, 16, 17]],
                      [[18, 19, 20],[21, 22, 23],[24, 25, 26]]])

tensor_3d = tf.convert_to_tensor(tensor_3d, dtype=tf.float64)
with tf.Session() as sess:
    print(tensor_3d.get_shape())
    print(sess.run(tensor_3d))
    print("\n")

interactive_session = tf.InteractiveSession()
tensor = np.array([1, 2, 3, 4, 5])
tensor = tf.constant(tensor)
print(tensor.eval())
interactive_session.close()

(10,)
[ 1  2  3  4  5  6  7  8  9 10]


(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3, 3)
[[[ 0.  1.  2.]
  [ 3.  4.  5.]
  [ 6.  7.  8.]]

 [[ 9. 10. 11.]
  [12. 13. 14.]
  [15. 16. 17.]]

 [[18. 19. 20.]
  [21. 22. 23.]
  [24. 25. 26.]]]


[1 2 3 4 5]
