Demo code to explain the basic concepts of Variables, contants and Placeholders

In [1]:
import tensorflow as tf

In [2]:
one=tf.constant(1)

In [3]:
print(one)

Tensor("Const:0", shape=(), dtype=int32)


In [4]:
ten=tf.Variable(10)

In [5]:
ten

<tf.Variable 'Variable:0' shape=() dtype=int32_ref>

In [6]:
#tensorflow offers mathematical methods like add
#there is also operator overloading..so you can also use zero+one
sum=tf.add(ten,one)
#sum=ten+one


In [7]:
#assign method is the equivalent of "=" ...so this is same as zero=sum
update=tf.assign(ten,sum)


In [8]:
#update1=tf.assign(one,sum)

In [9]:
#you need this when using Variables only
#if you are using contants and placeholders - you do not need this line of code

init_op=tf.global_variables_initializer()

In [10]:
sess=tf.Session()

In [11]:
sess.run(init_op)

In [12]:
print(sess.run(update))

11


In [13]:
print(sess.run(sum))

12


In [ ]:
#execute update-> ten=sum-> ten + one

In [17]:
import tensorflow as tf

first_value = tf.constant(1)
second_value = tf.Variable(10)
third_value = tf.add(second_value,first_value)

result = tf.assign(second_value,third_value)

init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)
print(sess.run(third_value))
print(sess.run(result))
print(sess.run(third_value))
print(sess.run(result))

11
11
12
12


In [ ]:
#Placeholders

In [16]:
#not initialized to any value - unlike constants and variables
a=tf.placeholder(tf.float32)

In [19]:
#you cannot create a variable this way
#z=tf.Variable(tf.float32)
#z=tf.constant(tf.float32)

In [20]:
a

<tf.Tensor 'Placeholder:0' shape=<unknown> dtype=float32>

In [21]:
b=a*2

In [24]:
#sess.run(b)

In [25]:
sess.run(b,feed_dict={a:3.0})

6.0

In [26]:
sess.run(b,feed_dict={a:[1,2,3,4]})

array([2., 4., 6., 8.], dtype=float32)

In [25]:
new = tf.placeholder(tf.float32)

new1 = new*2

sess.run(new1,feed_dict={new:2})

4.0

In [27]:
sess.run(new1,feed_dict={new:[2,3,4,5,6]})

array([ 4.,  6.,  8., 10., 12.], dtype=float32)

In [29]:
dictionary={new:[[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],[[13,14,15],[16,17,18],
                                                     [19,20,21],[22,23,24]]]}


In [30]:
result=sess.run(new1,feed_dict=dictionary)
print(result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]


In [31]:
sess.close()

In [34]:
with tf.Session() as sess: 
    result=sess.run(new1,feed_dict={new:3.5})   
    print(result)

7.0


In [35]:
with tf.Session() as sess: 
    result=sess.run(new1,feed_dict=dictionary)
    print(result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]
  [20. 22. 24.]]

 [[26. 28. 30.]
  [32. 34. 36.]
  [38. 40. 42.]
  [44. 46. 48.]]]
